jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: Setup Environment
          command: |
            docker build -t local/ros_zesty .

workflows:
  version: 2
  build:
    jobs:
      - build
